### ISSUE TITLE
Invoicing : cannot add list in headers/footers

### ISSUE THREAD

**Issue by tlartaud** [marvinlabs/customer-area#255]
When we try to add a list we got this

```
Fatal error: Uncaught Exception: TCPDF ERROR: Could not include font definition file: zapfdingbats in /srv/wpca-plugins/customer-area/libs/php/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php:2927 Stack trace: #0 /srv/wpca-plugins/customer-area/libs/php/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php(4275): TCPDF->Error('Could not inclu...') #1 /srv/wpca-plugins/customer-area/libs/php/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php(4436): TCPDF->AddFont('zapfdingbats', '', '', true) #2 /srv/wpca-plugins/customer-area/libs/php/html2pdf/_class/parsingCss.class.php(340): TCPDF->SetFont('zapfdingbats', '', 7.5) #3 /srv/wpca-plugins/customer-area/libs/php/html2pdf/html2pdf.class.php(5459): HTML2PDF_parsingCss->fontSet() #4 /srv/wpca-plugins/customer-area/libs/php/html2pdf/html2pdf.class.php(4584): HTML2PDF->_tag_open_TD(Array, 'li') #5 /srv/wpca-plugins/customer-area/libs/php/html2pdf/html2pdf.class.php(1294): HTML2PDF->_tag_open_LI(Array) #6 /srv/wpca-plugins/customer-area/libs/php/html2pdf/html2pdf.class.php(1249): HTML2PDF->_executeAction( in /srv/wpca-plugins/customer-area/libs/php/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php on line 2927
```

**Comment by vpratfr** [comment]
Fixed
